# Generated by Django 5.2.2 on 2025-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('CodEditorial', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('Codigo_Libro', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.TextField(max_length=15)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.FloatField()),
                ('CodEditorial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=30)),
                ('Casa', models.TextField(max_length=15)),
                ('Hechizo', models.TextField(max_length=20)),
                ('Imagen', models.ImageField(null=True, upload_to='Personajes')),
            ],
        ),
    ]
